name: Deployment

on:
  push:
    branches:
      - master
jobs:
  build:
    name: Deploy on push
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands to pull from master branch
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd public_html
          cd meem
          cd dashboard
          git pull origin master
