name: Production Deployment

on:
  push:
    branches:
      - production
jobs:
  build:
    name: Deploy on push
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands to pull from production branch
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_USERNAME }}
        key: ${{ secrets.PROD_KEY }}
        port: ${{ secrets.PROD_PORT }}
        script: |
          cd backend
          git pull origin production
